image: python:3.12

stages:
  - setup
  - unit
  - integration

setup-env:
  stage: setup
  dependencies:
    - setup-env
  script:
    - python -m venv venv
    - . venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  artifacts:
    paths:
      - venv/
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'


unit-tests:
  stage: unit
  script:
    - . venv/bin/activate
    - pytest ./app/tests/unit_tests
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'

integration-tests:
  stage: integration
  dependencies:
    - setup-env
  script:
    - . venv/bin/activate
    - pytest ./app/tests/integration_tests
  needs:
    - unit-tests
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
