version: "3"

services:
  app:
    build: ./app/
    image: ml-service-app:0.1
    env_file:
      - .env
    volumes:
      - ./app:/app
  web-proxy:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
  rabbitmq:
    image: rabbitmq:4-management-alpine
    hostname: rabbitmq
    restart: on-failure
    env_file:
      - .env
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  database:
    image: postgres:15-alpine
    hostname: database
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
  rabbitmq_volume:
