version: "3"

services:
  app:
    build: ./app/
    image: ml-service-app:latest
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
  web-proxy:
    build: ./web-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
  rabbitmq:
    image: rabbitmq:4-management-alpine
    hostname: rabbitmq
    restart: always
    env_file:
      - ./rabbitmq/.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  database:
    image: postgres:15-alpine
    hostname: database
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./database/.env
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
  rabbitmq_data:
